default:
    target: dev
    outputs:
      dev:
        type: postgres
        host: "{{ env_var('DB_HOST') }}"
        user: "{{ env_var('DB_USER') }}"
        pass: "{{ env_var('DB_PASSWORD') }}"
        port: "{{ env_var('DB_PORT') | int }}"
        dbname: "{{ env_var('DB_NAME') }}"
        schema: "{{ env_var('DB_SCHEMA') }}"
        threads: 1
        keepalives_idle: 0